// <auto-generated />
namespace University.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class moveteacherlink : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(moveteacherlink));
        
        string IMigrationMetadata.Id
        {
            get { return "201503220743553_move teacher link"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
